app:
  name: apigateway
  user_cookie: c_user

server:
   port: ${PORT:8888}
   
zuul:
  #Service will be mapped under the /api URI
  prefix: /api
#  Uncomment to disable auto-registering all services read from Eureka
#  ignoredServices: '*'
  routes:
    auth:
      path: /auth/**
      url: http://localhost:9991/auth/
      sensitive-headers:
    user:
      path: /user/**
      url: http://localhost:8080
      stripPrefix: false
      sensitiveHeaders:
     # serviceId: userservice
    todolist:
      path: /todolist/**
      url: http://localhost:8090
      stripPrefix: false
      sensitiveHeaders:
    todolistitem:
      url: http://localhost:8090
      path: /todolistitem/**
      stripPrefix: false
      sensitiveHeaders:
    # serviceId: todolistservice
  ignored-headers: Access-Control-Allow-Origin 
  
#security:
#  user:
#    password: none
#  oauth2:
#    client:
#      accessTokenUri: http://localhost:8888/api/auth/oauth/token
#      userAuthorizationUri: http://localhost:8888/api/auth/oauth/authorize
#      clientId: gateway
#      clientSecret: secret
#    resource:
#      jwt:
#        keyValue: |
#          -----BEGIN PUBLIC KEY-----
#          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAimUKhvBhsoeSM3HkIOP/Y3RXjvonBlZnLj8oO92TyAKG53lmAoK0wZ5MTZPsfrOz2Z7CeAp6mPhUANX2RUoFwVzG7rJmgWyqGmGFNBmtYL+uVqQ80TzWi5zyzXTxgVMWiCqqw/u4AeE1qhN8chnGwhUBnpgPAPd8v57mIwg0n5JxjdYe7pgHlpvt8ZXTXd1KBxB5K7WjNlCfMf75ZEeBaplxsSfJUwKbnHQKWcY3NnpjkVR8y4jviAbkOHmGMaliM7fcsLzbosBUPDQuNlvYdjPBRfH6MMPeXRW6On3u0Um9wIYmkQS+AEgHCq4UuLOnTTqqxnGkwFYeMAAXmRyMtQIDAQAB
#          -----END PUBLIC KEY-----

ribbon: 
  ConnectTimeout: 30000
  ReadTimeout: 990000
  maxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: false
    