app:
  name: apigateway
  user_cookie: c_user

spring:
   jackson:
      default-property-inclusion: non_null
   http:
       multipart:
         max-file-size: -1

server:
   port: ${PORT:8888}
   
zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  sensitiveHeaders: Cookie,Set-Cookie
#  Uncomment to disable auto-registering all services read from Eureka
#  ignoredServices: '*'
  routes:
    auth:
      path: /auth/**
      url: http://localhost:9991/
      strip-prefix: true
      sensitive-headers:
    user:
      path: /userservice/**
      serviceId: userservice
      #url: http://localhost:8080
      #strip-prefix: false
      sensitiveHeaders:
    todolist:
      path: /todolistservice/**
      url: http://localhost:8090
      #strip-prefix: false
      sensitiveHeaders:
    todolistitem:
      url: http://localhost:8090
      path: /todolistitem/**
      sensitiveHeaders:
      strip-prefix: false
    file:
      url: http://localhost:8086
      path: /file/**
      sensitiveHeaders:
      strip-prefix: false
    meeting:
      serviceId: meeting
      path: /meeting/**
      sensitiveHeaders:
      strip-prefix: false
    values:
      url: http://localhost:54633 
      path: /values/**
      sensitiveHeaders:
      strip-prefix: false
  ignored-headers: Access-Control-Allow-Origin
  addProxyHeaders: true
# based on https://gist.github.com/spencergibb/80a134b4738c78ca64e4d0c77214fcb6
meeting:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: localhost:8086
  

ribbon: 
  ConnectTimeout: 30000
  ReadTimeout: 990000
  maxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
    