server:
  port: 9991
  #contextPath: /auth

app:
  name: authserver
  user_cookie: c_user

jwt:
  header: Authorization
  expires_in: 120 # 5 minutes
  secret: queenvictoria
  cookie: AUTH-TOKEN
  refresh_token_expires_in: 300 


spring:
   jpa:
     database: POSTGRESQL
     show-sql: true 
     hibernate:
        naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
#postgres config
   datasource:
     platform: postgres 
     url: jdbc:postgresql://127.0.0.1:5432/userdb
     username: postgres
     password: admin
     driverClassName: org.postgresql.Driver
